export const images = {
  backGround: require('./Background.png'),
  hideicon: require('./Hideicon.png'),
  unhideicon: require('./Unhideicon.png'),
  homeicon: require('./Home.png'),
  favoriteicon: require('./Favorite.png'),
  notificationicon: require('./Notification.png'),
  chaticon: require('./Chat.png'),
  profileicon: require('./Profile.png'),
  Favoritefill: require('./Favoritefill.png'),
  Notificationfill: require('./Notificationfill.png'),
  Homefill: require('./Homefill.png'),
  Chatfill: require('./Chatfill.png'),
  Profilefill: require('./Profilefill.png'),
  HomeTitle: require('./HomeTitle.png'),
  HomeTitle2: require('./HomeTitle2.png'),
  Courtimg1: require('./Courtimg1.png'),
  Courtimg2: require('./Courtimg2.png'),
  SendIcon: require('./SendIcon.png'),
  InfoIcon: require('./Info.png'),
  // Court placeholder for courts without user photos
  courtPlaceholder: require('./Courtimg1.png'),
};
